import { EntityDefinition, FieldDefinition } from '../types/entity';
import * as prettier from 'prettier';

/**
 * Maps internal field types to TypeScript types.
 */
function mapFieldTypeToTS(field: FieldDefinition): string {
    switch (field.type) {
        case 'string':
            return 'string';
        case 'number':
            return 'number';
        case 'boolean':
            return 'boolean';
        case 'date':
            return 'string'; // ISO date string
        case 'reference':
            return 'string'; // ID of the referenced entity
        case 'enum':
            if (field.options && field.options.length > 0) {
                return field.options.map((opt) => `'${opt}'`).join(' | ');
            }
            return 'string';
        default:
            return 'any';
    }
}

/**
 * Generates the main interface for an entity.
 */
function generateMainInterface(name: string, def: EntityDefinition): string {
    const lines = [`export interface ${name} {`];

    // System fields
    lines.push(`  $id: string;`);
    lines.push(`  $createdAt: string;`);
    lines.push(`  $updatedAt: string;`);

    // User defined fields
    Object.entries(def.fields).forEach(([fieldName, fieldDef]) => {
        const tsType = mapFieldTypeToTS(fieldDef);
        const optional = !fieldDef.required ? '?' : '';
        lines.push(`  ${fieldName}${optional}: ${tsType};`);
    });

    lines.push(`}`);
    return lines.join('\n');
}

/**
 * Generates the Create DTO (omits system fields).
 */
function generateCreateDTO(name: string, def: EntityDefinition): string {
    const lines = [`export interface Create${name}DTO {`];

    Object.entries(def.fields).forEach(([fieldName, fieldDef]) => {
        const tsType = mapFieldTypeToTS(fieldDef);
        const optional = !fieldDef.required ? '?' : '';
        lines.push(`  ${fieldName}${optional}: ${tsType};`);
    });

    lines.push(`}`);
    return lines.join('\n');
}

/**
 * Generates the Update DTO (Partial Create DTO + ID).
 */
function generateUpdateDTO(name: string): string {
    return `export interface Update${name}DTO extends Partial<Create${name}DTO> {
  id: string;
}`;
}

/**
 * Generates the Filter DTO.
 */
function generateFilterDTO(name: string, def: EntityDefinition): string {
    const lines = [`export interface ${name}Filter {`];

    Object.entries(def.fields).forEach(([fieldName, fieldDef]) => {
        const tsType = mapFieldTypeToTS(fieldDef);
        lines.push(`  ${fieldName}?: ${tsType};`);
    });

    lines.push(`}`);
    return lines.join('\n');
}

/**
 * Generates all TypeScript definitions for an entity.
 */
export async function generateTypes(entityName: string, entityDef: EntityDefinition): Promise<string> {
    // Capitalize entity name for interface names (e.g., "tournament" -> "Tournament")
    const pascalName = entityName.charAt(0).toUpperCase() + entityName.slice(1);

    const code = [
        `/**`,
        ` * Auto-generated type definitions for ${pascalName}`,
        ` * Generated by Grimoire Entity System`,
        ` */`,
        ``,
        generateMainInterface(pascalName, entityDef),
        ``,
        generateCreateDTO(pascalName, entityDef),
        ``,
        generateUpdateDTO(pascalName),
        ``,
        generateFilterDTO(pascalName, entityDef),
        ``
    ].join('\n');

    // Format with Prettier
    return prettier.format(code, {
        parser: 'typescript',
        printWidth: 100,
        tabWidth: 2,
        singleQuote: true,
        trailingComma: 'all',
    });
}
